liquibase:
    context: production

spring:
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/spring_mt?createDatabaseIfNotExist=true
        poolName: SpringBootHikariCP
        username: root
        password: root
        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.hbm2ddl.auto: validate

logging:
    level:
        me.lcardito.spring: DEBUG
        org.springframework.security: DEBUG
